### ISSUE TITLE
"ERROR: Could not find a version that satisfies the requirement dr-doc-search (from versions: none)" on Colab Notebook

### ISSUE THREAD

**Issue by stevevaius2015** [namuan/dr-doc-search#14]
I received an error while trying to install this library on colab via `pip install dr-doc-search` as `ERROR: Could not find a version that satisfies the requirement dr-doc-search (from versions: none)`. Is there any problem with this method of installation?

**Comment by namuan** [comment]
Found that the default version used in Google Colab was lower than the one supported. I have now included `3.8` in the supported version so it should work now on Google Colab

![Screenshot 2023-02-18 at 21 18 29@2x](https://user-images.githubusercontent.com/575441/219900033-891009d1-2fa4-4e77-a661-60e5d3771350.png)

![Screenshot 2023-02-18 at 21 19 58@2x](https://user-images.githubusercontent.com/575441/219900051-0e7051a1-4a4d-4a94-babc-e3baae073050.png)
