### ISSUE TITLE
"No matching distribution found for dr-doc-search" on Google Colab.

### ISSUE THREAD

**Issue by ishanyash** [namuan/dr-doc-search#16]
"!pip install dr-doc-search" doesn’t work on Google Colab and even on my JuPyter Notebook.
This is what I get When I try the aforementioned :

"Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement dr-doc-search (from versions: none)
ERROR: No matching distribution found for dr-doc-search
"

**Comment by namuan** [comment]
Found that the default version used in Google Colab was lower than the one supported. I have now included `3.8` in the supported version so it should work now on Google Colab

![Screenshot 2023-02-18 at 21 18 29@2x](https://user-images.githubusercontent.com/575441/219900033-891009d1-2fa4-4e77-a661-60e5d3771350.png)

![Screenshot 2023-02-18 at 21 19 58@2x](https://user-images.githubusercontent.com/575441/219900051-0e7051a1-4a4d-4a94-babc-e3baae073050.png)
