### ISSUE TITLE
Different providers?

### ISSUE THREAD

**Issue by xloem** [namuan/dr-doc-search#8]
It would be pleasant to be able to use different backends than OpenAI. Training a model locally, even.

**Comment by namuan** [comment]
From v1.5.0, it now supports HuggingFace for embedding and generating text hence providing the ability to run everything locally.

Here is the command to train with `huggingface`

```shell
dr-doc-search --train -i ~/Downloads/parable-of-a-monetary-economy-heteconomist.pdf --embedding huggingface
```

And then use `huggingface` pipeline for text generation. It uses `pszemraj/long-t5-tglobal-base-16384-book-summary` model in the pipeline but should be easy to switch/parameterise if you can find a better one.

```shell
dr-doc-search --web-app -i ~/Downloads/parable-of-a-monetary-economy-heteconomist.pdf --llm huggingface -v
```

Let me know what you think
